### ISSUE TITLE
update LICENSE to Perl 5 License

### ISSUE THREAD

**Issue by KohaAloha** [ronsavage/Data-Session#1]
hi Ron
we are working thru packaging Data-Session for debian

attached is a patch to update the ./LICENSE to the The Perl 5 License (Artistic 1 & GPL 1)

	https://dev.perl.org/licenses/

	--------------------------------------------------------------
	 Perl5 is Copyright (C) 1993-2005, by Larry Wall and others.

	It is free software; you can redistribute it and/or modify it under the terms of either:

	a) the GNU General Public License as published by the Free Software Foundation; either version 1, or (at your option) any later version, or

	b) the "Artistic License". 
	--------------------------------------------------------------

you can track progress here...
 https://salsa.debian.org/perl-team/modules/packages/libdata-session-perl

cheers, Mason

**Comment by KohaAloha** [comment]
patch added at PR #2

**Comment by ronsavage** [comment]
I've merged a couple of patches, but I'm confused about why this one is not in a file-diff format.
Do you want me to apply is as is, or are you still working on this one?

**Comment by KohaAloha** [comment]
hi Ron, sorry for the confusion

the patch for this issue is 'attached' with PR #2, which is now merged - so, we can close this issue :)
